### ISSUE TITLE
feedback: Управление VPN-туннелями | VK Cloud

### ISSUE THREAD

**Issue by gibsdevel** [vk-cs/docs-public#107]
> openstack vpn service

Пропущено set после service, пример как должно быть
openstack vpn service set ab05ddaf-02bf-4dee-88c6-29ccb867eea4 --disable

Исправить в вариантах Linux/macOS (bash, zsh) и Windows (PowerShell)

[https://cloud.vk.com/docs/networks/vnet/operations/manage-vpn#26589-tabpanel-0](https://cloud.vk.com/docs/networks/vnet/operations/manage-vpn#26589-tabpanel-0)

**Comment by DaryaDymbrylova** [comment]
Спасибо за внимательность! Изменения внесены
