### ISSUE TITLE
feedback: Файловые менеджеры | VK Cloud

### ISSUE THREAD

**Issue by e-burlakina** [vk-cs/docs-public#108]
> Cloude Storage

Cloud Storage

[https://cloud.vk.com/docs/ru/base/s3/storage-connecting/s3-file-managers](https://cloud.vk.com/docs/ru/base/s3/storage-connecting/s3-file-managers)

**Comment by DaryaDymbrylova** [comment]
Спасибо за внимательность! Внесли изменения.
