### ISSUE TITLE
feedback: Получение токена доступа | VK Cloud

### ISSUE THREAD

**Issue by e-burlakina** [vk-cs/docs-public#110]
> Единственный риск использования такого токена является то, что при подборе...

Единственным риском использования такого токена является то, что при подборе...

[https://cloud.vk.com/docs/ru/ml/cloud-voice/get-voice-token](https://cloud.vk.com/docs/ru/ml/cloud-voice/get-voice-token)

**Comment by DaryaDymbrylova** [comment]
Спасибо за внимательность! Внесли изменения.
