### ISSUE TITLE
feedback: Публичный DNS | VK Cloud

### ISSUE THREAD

**Issue by Piknik1990** [vk-cs/docs-public#122]
> curl --location 'https://mcs.mail.ru/public-dns/v2/dns/12f67238-XXXX-XXXX-XXXX-227afa2eb8dd/a/' \
--header 'X-Auth-Token: gAAAAABlLjgzyxXXXX' \
--header 'Content-Type: application/json' \
--data '{"name": "@", 
"ipv4": "8.8.8.13",
"ttl": 60
}'

Не хватает ключа с методом "-X POST"

[https://cloud.vk.com/docs/networks/dns/publicdns#9913-tabpanel-1](https://cloud.vk.com/docs/networks/dns/publicdns#9913-tabpanel-1)

**Comment by DaryaDymbrylova** [comment]
Спасибо за комментарий. В примерах запросов GET и POST мы, действительно, не используем ключи с указанием метода. Это допускает спецификация cURL:

_Normally you do not need this option. All sorts of GET, HEAD, POST and PUT requests are rather invoked by using dedicated command line options. This option only changes the actual word used in the HTTP request, it does not alter the way curl behaves._ 

См. подробнее: https://curl.se/docs/manpage.html

**Comment by DaryaDymbrylova** [comment]
Закрываю
