### ISSUE TITLE
feedback: Производительность дисков VK Cloud | VK Cloud

### ISSUE THREAD

**Issue by jingvar** [vk-cs/docs-public#133]
> 64K
45000
500
30000
500
1M
45000
500
30000
500

Вы уверены что при разных блоках одинаковые значения iops и скорость будет?

[https://cloud.vk.com/docs/base/iaas/concepts/volume-sla#testirovanie_proizvoditelnosti_diskov](https://cloud.vk.com/docs/base/iaas/concepts/volume-sla#testirovanie_proizvoditelnosti_diskov)

**Comment by Olga-Alekseenko** [comment]
Здравствуйте! Не могли бы вы уточнить ваш вопрос. Честно говоря, в том разделе, на который вы ссылаетесь, я не вижу утверждения, что при разных блоках будут одинаковые значения iops и скорость.

**Comment by Olga-Alekseenko** [comment]
В документации все верно, изменений не требуется
