### ISSUE TITLE
feedback: Настройки кластера | VK Cloud

### ISSUE THREAD

**Issue by nata-documentat** [vk-cs/docs-public#136]
> Настройки кластера

В `settings.meta.json` в поле `sectionTitle` в конце стоит точка, которой быть не должно.

https://cloud.vk.com/docs/kubernetes/k8s/concepts/addons-and-settings/settings — проблема с точкой видна здесь, в меню навигации слева.

[https://cloud.vk.com/docs/kubernetes/k8s/concepts/addons-and-settings/settings](https://cloud.vk.com/docs/kubernetes/k8s/concepts/addons-and-settings/settings)

**Comment by DaryaDymbrylova** [comment]
Точку убрали. Спасибо, Ната. Задачу закрываю
