### ISSUE TITLE
feedback: Развертывание Ingress-контроллера с TCP-балансировщиком | VK Cloud

### ISSUE THREAD

**Issue by nata-documentat** [vk-cs/docs-public#141]
> Чтобы развернуть демо-приложения:

Во 2 подразделе и во всех последующих некорректно отображается нумерация в списках (например, здесь начинается с шага 5.1).

[https://cloud.vk.com/docs/ru/kubernetes/k8s/how-to-guides/ingress/ingress-tcp](https://cloud.vk.com/docs/ru/kubernetes/k8s/how-to-guides/ingress/ingress-tcp)

![image](https://github.com/vk-cs/docs-public/assets/79202337/d639390a-5f96-4529-819e-d723f4ecd0bf)

**Comment by Olga-Alekseenko** [comment]
Создан запрос разработчикам на устранение ошибки в движке отображения документации
