### ISSUE TITLE
feedback: Создание файла kubeconfig для сервисного аккаунта | VK Cloud

### ISSUE THREAD

**Issue by SaintJacques** [vk-cs/docs-public#146]
>  user: <данные для аутентификации>

```yaml
user:
  token: <данные для аутентификации>
```

[https://cloud.vk.com/docs/kubernetes/k8s/how-to-guides/sa-kubeconfig](https://cloud.vk.com/docs/kubernetes/k8s/how-to-guides/sa-kubeconfig)

**Comment by eeirich** [comment]
Правка внесена: https://cloud.vk.com/docs/kubernetes/k8s/how-to-guides/sa-kubeconfig#4_sozdayte_kubeconfig_dlya_servisnogo_akkaunta

**Comment by eeirich** [comment]
Правка внесена: https://cloud.vk.com/docs/kubernetes/k8s/how-to-guides/sa-kubeconfig#4_sozdayte_kubeconfig_dlya_servisnogo_akkaunta
