### ISSUE TITLE
feedback: Установка Docker CE на операционную систему Ubuntu | VK Cloud

### ISSUE THREAD

**Issue by hmnvdk** [vk-cs/docs-public#148]
> Убедитесь, что репозиторий был подключен успешно:

Скопировать

нужно обновить кэш перед проверкой sudo apt update

[https://cloud.vk.com/docs/ru/cases/cases-docker-ce/docker-ce-u18](https://cloud.vk.com/docs/ru/cases/cases-docker-ce/docker-ce-u18)

**Comment by DaryaDymbrylova** [comment]
Привет. Спасибо за комментарий. Поправили: https://cloud.vk.com/docs/cases/cases-docker-ce/docker-ce-u18
