### ISSUE TITLE
feedback: Подключение к БД | VK Cloud

### ISSUE THREAD

**Issue by avk777** [vk-cs/docs-public#153]
> Установите JDBC-драйвер для PostgreSQL.

не рабочая ссылка 404

[https://cloud.vk.com/docs/dbs/dbaas/connect#1064-tabpanel-3](https://cloud.vk.com/docs/dbs/dbaas/connect#1064-tabpanel-3)

**Comment by eeirich** [comment]
Изменения внесены: https://cloud.vk.com/docs/dbs/dbaas/connect#1064-tabpanel-3
