### ISSUE TITLE
feedback: Create | VK Cloud

### ISSUE THREAD

**Issue by andreyaksenov** [vk-cs/docs-public#165]
> | Parameter name | Description | |------------------------------------|

Рендеринг таблицы сломан в английской версии страницы.

[https://cloud.vk.com/docs/en/dbs/adb/quick-start/create-adb](https://cloud.vk.com/docs/en/dbs/adb/quick-start/create-adb)

![image](https://github.com/user-attachments/assets/b1207820-b559-4eef-a9b4-4213b2fbb7e6)

**Comment by Olga-Alekseenko** [comment]
Спасибо за внимательность)) Все исправлено

**Comment by Olga-Alekseenko** [comment]
Сделано
