### ISSUE TITLE
feedback: Подключение к Linux ВМ - VK Cloud

### ISSUE THREAD

**Issue by gibsdevel** [vk-cs/docs-public#48]
> Операционная система	Логин
Bitrix* root*
CentOS centos
Debian debian
Fedora fedora
FreeBSD freebsd
Ubuntu ubuntu

**Добавить к записям** 
Almalinux   almalinux

[https://mcs.mail.ru/docs/base/iaas/vm-start/vm-connect/vm-connect-nix](https://mcs.mail.ru/docs/base/iaas/vm-start/vm-connect/vm-connect-nix)

**Comment by vkborzilova** [comment]
добавлено, закрываю issue
