### ISSUE TITLE
feedback: Резервное копирование с помощью Velero — VK Cloud | VK Cloud

### ISSUE THREAD

**Issue by aleksandr-oliferuk** [vk-cs/docs-public#52]
> openstack volume show <идентификатор диска>

openstack volume show <идентификатор диска> --fit-width
# ключ --fit-width подгоняет вывод команды под размер терминала

[https://mcs.mail.ru/docs/base/k8s/use-cases/velero-backup#](https://mcs.mail.ru/docs/base/k8s/use-cases/velero-backup#)

**Comment by vkborzilova** [comment]
@aleksandr-oliferuk  В остальных статьях этот параметр не используется, чем обоснована его необходимость в этом месте?

**Comment by vkborzilova** [comment]
Ответа по комментарию не поступало более месяца, заявку закрываю

**Comment by aleksandr-oliferuk** [comment]
Привет! Давно не заходил в свой гитхаб. Этот параметр делаю вывод в терминале гораздо более pretty.  Попробуйте и убедитесь сами!

**Comment by gibsdevel** [comment]
Пример
![image](https://github.com/vk-cs/docs-public/assets/32682306/69c1877f-b91c-4f5b-ae9e-132220784acf)
и
![image](https://github.com/vk-cs/docs-public/assets/32682306/354de568-e037-42de-a456-d11a000515bd)

**Comment by vkborzilova** [comment]
Спасибо за пояснение!

Посмотрим остальные вхождения и внесем изменения при необходимости

**Comment by vkborzilova** [comment]
добавлено, issue закрываю
