### ISSUE TITLE
feedback: Производительность дисков VK Cloud | VK Cloud

### ISSUE THREAD

**Issue by gibsdevel** [vk-cs/docs-public#65]
> --rw=randwrite \

Должно быть  --rw=randread \ 

[https://mcs.mail.ru/docs/base/iaas/concepts/volume-sla#16189-5](https://mcs.mail.ru/docs/base/iaas/concepts/volume-sla#16189-5)

**Comment by vkborzilova** [comment]
Учтено в рамках https://github.com/vk-cs/docs-public/commit/683e934a5c304a2d19090bbca4ac6cd2c8d9ee9b, закрываю
