### ISSUE TITLE
feedback: Примеры манифестов | VK Cloud

### ISSUE THREAD

**Issue by Piknik1990** [vk-cs/docs-public#80]
>  ключевой пары для инстанса. Можно узнать с помощью команды: openstack keypair 
list

Слово "list" перешло на новую строку и сломала синтаксис

[https://mcs.mail.ru/docs/manage/tools-for-using-services/terraform/reference/examples#](https://mcs.mail.ru/docs/manage/tools-for-using-services/terraform/reference/examples#)

**Comment by vkborzilova** [comment]
Спасибо за внимательность! Изменения внесены, issue закрыт автоматически
