### ISSUE TITLE
feedback: Использование Terraform | VK Cloud

### ISSUE THREAD

**Issue by Piknik1990** [vk-cs/docs-public#81]
> Подробнее в документации Terraform-провайдера.

Тут 404 вылетает по ссылке

[https://mcs.mail.ru/docs/base/k8s/operations/helpers/terraform-howto#kak_nachat_polzovatsya_terraform](https://mcs.mail.ru/docs/base/k8s/operations/helpers/terraform-howto#kak_nachat_polzovatsya_terraform)

**Comment by vkborzilova** [comment]
@Piknik1990 при воспроизведении ошибки ссылка https://github.com/vk-cs/terraform-provider-vkcs/tree/master/docs рабочая

Прошу проверить повторно, проблема сохраняется?

**Comment by vkborzilova** [comment]
прошу прощения, сбила с толку ссылка, проверено не там. Возьмем в работу, спасибо

**Comment by vkborzilova** [comment]
изменения внесены
