### ISSUE TITLE
feedback: Installing and configuring PostgreSQL on Ubuntu | VK Cloud

### ISSUE THREAD

**Issue by LavTeamProject** [vk-cs/docs-public#82]
> apt key

sudo apt-key add -

[https://mcs.mail.ru/docs/en/additionals/cases/cases-db-config/case-psql-create](https://mcs.mail.ru/docs/en/additionals/cases/cases-db-config/case-psql-create)

**Comment by vkborzilova** [comment]
комментарий неактуален в связи с полным обновлением статьи
