### ISSUE TITLE
Terraform Создание ВМ выбор подсети

### ISSUE THREAD

**Issue by BybonAnton** [vk-cs/docs-public#84]
Добрый день подскажите не нашёл в инструкии как при использовании terraform указать новой создаваемой ВМ какую подсеть использовать, 
Напримет есть сеть main в нейт 4 подсети 1.2.3.4 
при создании ВМ указываю   network {   name = main  }} тогда ВМ использует 1 подсеть, а как сделать чтобы использовал например 3 подсеть при создании.

**Comment by Shaverdoff** [comment]
в
resource "vkcs_networking_port" "persistent_etcd" {
использовать конструкцию
fixed_ip {
    subnet_id = vkcs_networking_subnet.db.id
  }
}
пробовали?

**Comment by BybonAnton** [comment]
> описать эти подсети через data и в resource "vkcs_networking_port" "persistent_etcd" { использовать конструкцию fixed_ip { subnet_id = data.vkcs_networking_subnet.имя-подсети-в-тф.id } } пробовали?

Спасибо попробую.

**Comment by BybonAnton** [comment]
Спасибо всё сделал.
+ дополнительно добавил в network {
port = vkcs_networking_port.port.id }
