### ISSUE TITLE
feedback: Организация VPN-туннеля | VK Cloud

### ISSUE THREAD

**Issue by zibiv** [vk-cs/docs-public#92]
> Укажите в файле /etc/ipsec.secret ключ совместного использования (PSK). Ключ должен совпадать с ключом, указанным ранее:

файл называется ipsec.secrets

[https://cloud.vk.com/docs/networks/vnet/use-cases/vpn-tunnel#4969-tabpanel-2](https://cloud.vk.com/docs/networks/vnet/use-cases/vpn-tunnel#4969-tabpanel-2)

**Comment by vkborzilova** [comment]
исправлено, изменения на проде
