### ISSUE TITLE
feedback: Организация VPN-туннеля | VK Cloud

### ISSUE THREAD

**Issue by zibiv** [vk-cs/docs-public#93]
> Нажмите кнопку Добавить интерфейс

Должно быть "Добавить маршрут"

[https://cloud.vk.com/docs/networks/vnet/use-cases/vpn-tunnel#8947-tabpanel-1](https://cloud.vk.com/docs/networks/vnet/use-cases/vpn-tunnel#8947-tabpanel-1)

**Comment by vkborzilova** [comment]
исправлено, изменения на проде
