### ISSUE TITLE
feedback: Подключение к кластеру с помощью kubectl | VK Cloud

### ISSUE THREAD

**Issue by kiper-prog** [vk-cs/docs-public#96]
> https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh

503 Service Unavailable
No server is available to handle this request.

[https://cloud.vk.com/docs/base/k8s/connect/kubectl#6235-tabpanel-1](https://cloud.vk.com/docs/base/k8s/connect/kubectl#6235-tabpanel-1)

**Comment by vkborzilova** [comment]
@kiper-prog обратитесь, пожалуйста, в техническую поддержу

Возникли временные технические проблемы на сервере
